version: '3.3'

services:
  id-service:
    build:
      context: ./overture-id-service/src
      dockerfile: Dockerfile-dev
    restart: always
    environment:
      SERVICE_PORT: $ID_SERVICE_PORT
      SOURCE_LOGGER: console_debug
    volumes:
      - ./overture-id-service/src:/opt/app
    networks:
      - overture

networks:
  overture: