version: '3.4'
services:
  base-ubuntu:
    image: overture/local-base-ubuntu:latest
    build: ./docker-demo/base-ubuntu
    networks:
      - overture
  base-db:
    image: overture/local-base-db:latest
    build: ./docker-demo/base-db
    command: echo "do nothing"
    networks:
      - overture
  song-db:
    image: "postgres:9.6"
    environment:
      PGPORT: 8082
      POSTGRES_DB: song
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - overture
  id-db:
    build: ./docker-demo/id-db
    environment:
      PGPORT: 8088
      POSTGRES_DB: dcc_identifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - base-db
    volumes:
      - "id-db-data:/var/lib/postgresql/data/pgdata"
    networks:
      - overture
  auth:
    build: ./docker-demo/auth
    environment:
      AUTH_PORT: 8084
    volumes:
      - "auth-data:/opt/dcc/auth_data"
    networks:
      - overture
  id:
    build: ./docker-demo/id
    environment:
      ID_PORT: 8086
      ID_JMX_PORT: 10017
      ID_MANAGEMENT_PORT: 8089
      POSTGRES_HOST: id-db
      POSTGRES_PORT: 8088
      POSTGRES_DB: dcc_identifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      AUTH_SERVER_URL: http://auth:8084/check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
    depends_on:
      - base-ubuntu
      - id-db
      - auth
    volumes:
      - "./docker-demo/logs/id_logs:/opt/dcc/id_logs"
      - "./docker-demo/tools:/opt/dcc/tools"
    networks:
      - overture
  song:
    build:
      context: ./SONG
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default,local"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://song-db:8082/song?stringtype=unspecified"
      SONG_SECURITY_ENABLED: "false"
    env_file:
      - song_server.env
    restart: always
    depends_on:
      - song-db 
      - id
      - auth
    volumes:
      - "./docker-demo/logs/server_logs:/opt/dcc/server_logs"
      - "./docker-demo/tools:/opt/dcc/tools"
    networks:
      - overture
  song-maven:
    image: maven:3.5-jdk-11-slim
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./SONG:/opt
    working_dir: /opt
    env_file:
      - song_server.env
    depends_on:
      - song-db 
      - id
      - auth
    stdin_open: true
    tty: true
    command: ["bash"]
    entrypoint: [""]
    networks:
      - overture
  song-client:
    build:
      context: ./SONG
      dockerfile: Dockerfile
      target: client
    environment:
      CLIENT_ACCESS_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      CLIENT_SERVER_URL: http://song:8080
      CLIENT_STUDY_ID: ABC123
      CLIENT_DEBUG_ENABLED: "false"
    depends_on:
      - base-ubuntu
      - song
    volumes:
      - "./docker-demo/data/client:/opt/dcc/data"
      - "./docker-demo/tools:/opt/dcc/tools"
    stdin_open: true
    tty: true
    command: ["bash"]
    entrypoint: [""]
    networks:
      - overture
  object-storage:
    image: minio/minio:RELEASE.2018-05-11T00-29-24Z
    volumes:
      - "./docker-demo/data/minio:/opt/dcc/data"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PORT: 8085
    deploy:
        restart_policy:
            delay: 10s
            max_attempts: 10
            window: 60s
    command: server --address=0.0.0.0:8085 /opt/dcc/data
    networks:
      - overture
  storage-server:
    build: ./docker-demo/storage-server
    environment:
      OBJECT_STORAGE_URL: http://object-storage:8085
      OBJECT_STORAGE_ACCESS_KEY: minio
      OBJECT_STORAGE_SECRET_KEY: minio123
      AUTH_SERVER_URL: http://auth:8084/check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
      SERVER_URL: http://song:8080
      STORAGE_SERVER_PORT: 8087
      STORAGE_SERVER_JMX_PORT: 10018
      STORAGE_SERVER_DATA_BUCKET: oicr.icgc.test
      STORAGE_SERVER_STATE_BUCKET: oicr.icgc.test
      STORAGE_SERVER_DATA_DIR: data
      STORAGE_SERVER_OBJECT_SENTINEL: heliograph
    depends_on:
      - base-ubuntu
      - object-storage
      - song
      - auth
    volumes:
      - "./docker-demo/logs/storage_server_logs:/opt/dcc/storage_server_logs"
      - "./docker-demo/tools:/opt/dcc/tools"
      - "./docker-demo/data:/opt/dcc/data"
    networks:
      - overture
  storage-client:
    build: ./docker-demo/storage-client
    environment:
      AUTH_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      SERVER_URL: http://song:8080
      STORAGE_SERVER_URL: http://storage-server:8087
    depends_on:
      - storage-server
      - song
    volumes:
      - "./docker-demo/data/storage-client:/opt/dcc/data"
      - "./docker-demo/tools:/opt/dcc/tools"
    networks:
      - overture

volumes:
  db-data: {}
  id-db-data: {}
  auth-data: {}

networks:
  overture: