version: '3.3'

services:
  elasticsearch:
    image: elasticsearch:6.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - overture

networks:
  overture:

volumes:
  elasticsearch:
    driver: local